# Generated by Django 3.1.4 on 2021-02-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_resum'),
    ]

    operations = [
        migrations.AddField(
            model_name='resum',
            name='email',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='resum',
            name='mob',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
