# Generated by Django 3.1.4 on 2021-02-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_pencustomers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobno',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
