# Generated by Django 3.1.4 on 2021-03-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210228_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='resum',
            name='bpass',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='resum',
            name='bper',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='resum',
            name='btechcourse',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='resum',
            name='degclgname',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='resum',
            name='dob',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='resum',
            name='intclgname',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='resum',
            name='ipass',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='resum',
            name='iper',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='resum',
            name='p1name',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='resum',
            name='p2name',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='resum',
            name='s1name',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='resum',
            name='s2name',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='resum',
            name='s3name',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='resum',
            name='s4name',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='resum',
            name='spass',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='resum',
            name='sper',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='resum',
            name='sscclgname',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
