# Generated by Django 3.1.4 on 2021-03-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210306_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resum',
            old_name='btechcourse',
            new_name='bcourse',
        ),
    ]
