# Generated by Django 3.1.4 on 2021-03-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210306_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='resum',
            name='address',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='resum',
            name='gender',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
