# Generated by Django 3.1.4 on 2021-03-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210306_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cupiid',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
