# Generated by Django 3.1.4 on 2021-03-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_customer_cupiid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='url',
            field=models.URLField(default=1, max_length=100),
        ),
    ]
