# Generated by Django 3.1.4 on 2021-03-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_customer_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(default=1, max_length=50)),
                ('empoff', models.CharField(default=1, max_length=50)),
                ('workinghours', models.CharField(default=1, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='lot',
        ),
        migrations.DeleteModel(
            name='pencustomers',
        ),
        migrations.DeleteModel(
            name='resum',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
    ]
