# Generated by Django 3.1.4 on 2021-03-31 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210326_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='empoff',
            new_name='mobileno',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='workinghours',
        ),
    ]
